---
- name: Install Redis
  yum: name=redis state=present
  sudo: True
- name: Bind to 0.0.0.0
  lineinfile: >
    dest=/etc/redis.conf
    regexp="^bind"
    line="bind 0.0.0.0"
    state=present
  sudo: True
- name: Start Redis
  service: name=redis state=started enabled=yes
  sudo: True
