---
- name: Enable httpd_can_network_connect in SELinux
  seboolean: name=httpd_can_network_connect state=yes persistent=yes
  sudo: True
- name: Confirm the existence of the SSL directory
  file: path=/etc/nginx/ssl state=directory mode=700 owner=root group=root
  sudo: True
- name: Copy the SSL certificates
  copy: src={{item}}.crt dest=/etc/nginx/ssl/{{item}}.crt mode=600 owner=root group=root
  with_items: reverse_proxy_ssl_certificates
  sudo: True
  notify:
    - reload nginx
- name: Copy the SSL keys
  copy: src={{item}}.key dest=/etc/nginx/ssl/{{item}}.key mode=600 owner=root group=root
  with_items: reverse_proxy_ssl_certificates
  sudo: True
  notify:
    - reload nginx
- name: Copy the dhparam key
  copy: src=dhparam.pem dest=/etc/nginx/ssl/dhparam.pem mode=600 owner=root group=root
  sudo: True
  notify:
    - reload nginx
- name: Update Nginx config
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
  sudo: True
  notify:
    - reload nginx
- name: Update Nginx Site configs
  template: src={{item}}.j2 dest=/etc/nginx/conf.d/{{item}}.conf
  with_items: reverse_proxy_nginx_confs
  sudo: True
  notify:
    - reload nginx
