---
- hosts: wintergarten
  user: deploy
  vars:
    version: 5875691635208e390da0e58557e121ca443cc761
    bucket: releases.wintergarten
    port: 5000
    cache_ttl: 3600
    cache_address: 127.0.0.1:6379
    cache_enabled: true
  roles:
  - stunnel-client
  - nginx
  - wintergarten
