---
- hosts: app
  vars:
    site_confs:
      - { conf: 'citruspi.io' }
      - { conf: 'rhokthehood.com' }
    app_confs:
      - { conf: 'wintergarten.conf' }
    supervisor_confs:
      - { conf: 'wintergarten' }
      - { conf: 'rhokthehood-beta' }
    python_projects:
      - { domain: 'citruspi.io', subdomain: 'wintergarten-api', repo: 'https://github.com/citruspi/Wintergarten-API.git', branch: 'master' }
      - { domain: 'rhokthehood.com', subdomain: 'beta', repo: 'https://github.com/citruspi/RHokTheHood.git', branch: 'pythonification' }
  user: deploy
  roles:
  - nginx
  - git
  - pip
  - virtualenv
  - supervisor
  tasks:
  - name: Create Python project directories
    file: state=directory path=/apps/{{item.domain}}/{{item.subdomain}}
    with_items: python_projects
    sudo: True
  - name: Git clone Python projects
    git: repo={{item.repo}} dest=/apps/{{item.domain}}/{{item.subdomain}} version={{item.branch}}
    with_items: python_projects
    sudo: True
  - name: Install dependencies for Python projects
    pip: requirements=/apps/{{item.domain}}/{{item.subdomain}}/requirements.txt virtualenv=/venvs/{{item.domain}}/{{item.subdomain}}/venv
    with_items: python_projects
    sudo: True
  - name: Install Gunicorn for Python projects
    pip: name=gunicorn virtualenv=/venvs/{{item.domain}}/{{item.subdomain}}/venv
    with_items: python_projects
    sudo: True
  - name: Update Supervisord configs
    template: src=templates/apps/supervisor/{{item.conf}}.ini dest=/etc/supervisord.d/{{item.conf}}.ini
    with_items: supervisor_confs
    sudo: True
  - name: Update App configs
    template: src=templates/apps/confs/{{item.conf}}.j2 dest=/etc/{{item.conf}}
    with_items: app_confs
    sudo: True
  - name: Reload Supervisord processes
    supervisorctl: name={{item.conf}} state=present
    with_items: supervisor_confs
    sudo: True
  - name: Start Supervisord processes
    supervisorctl: name={{item.conf}} state=restarted
    with_items: supervisor_confs
    sudo: True
  - name: Update Nginx Site configs
    template: src=templates/apps/nginx/{{item.conf}}.j2 dest=/etc/nginx/conf.d/{{item.conf}}.conf
    with_items: site_confs
    sudo: True
    notify:
      - reload nginx
  handlers:
  - name: reload nginx
    command: service nginx reload
    sudo: True
