---
- hosts: app
  vars_files:
  - variables/app.yaml
  user: deploy
  roles:
  - nginx
  - git
  - pip
  - virtualenv
  - supervisor
  - stunnel
  tasks:
  - name: Create Python project directories
    file: state=directory path=/apps/{{item.domain}}/{{item.subdomain}}
    with_items: python_projects
    sudo: True
  - name: Git clone Python projects
    git: repo={{item.repo}} dest=/apps/{{item.domain}}/{{item.subdomain}} version={{item.branch}}
    with_items: python_projects
    sudo: True
  - name: Install dependencies for Python projects
    pip: requirements=/apps/{{item.domain}}/{{item.subdomain}}/requirements.txt virtualenv=/venvs/{{item.domain}}/{{item.subdomain}}/venv
    with_items: python_projects
    sudo: True
  - name: Install Gunicorn for Python projects
    pip: name=gunicorn virtualenv=/venvs/{{item.domain}}/{{item.subdomain}}/venv
    with_items: python_projects
    sudo: True
  - name: Update Supervisord configs
    template: src=templates/apps/supervisor/{{item.conf}}.ini dest=/etc/supervisord.d/{{item.conf}}.ini
    with_items: supervisor_confs
    sudo: True
  - name: Update App configs
    template: src=templates/apps/confs/{{item.conf}}.j2 dest=/etc/{{item.conf}}
    with_items: app_confs
    sudo: True
  - name: Reload Supervisord processes
    supervisorctl: name={{item.conf}} state=present
    with_items: supervisor_confs
    sudo: True
  - name: Start Supervisord processes
    supervisorctl: name={{item.conf}} state=restarted
    with_items: supervisor_confs
    sudo: True
  - name: Update Nginx Site configs
    template: src=templates/apps/nginx/{{item.conf}}.j2 dest=/etc/nginx/conf.d/{{item.conf}}.conf
    with_items: site_confs
    sudo: True
    notify:
      - reload nginx
  - name: Copy the Stunnel config
    template: src=templates/apps/stunnel/stunnel.conf.j2 dest=/etc/stunnel/stunnel.conf
    sudo: True
    notify:
      - reload stunnel
  handlers:
  - name: reload nginx
    command: service nginx reload
    sudo: True
  - name: reload stunnel
    command: service stunnel reload
    sudo: True
