---
- hosts: load-balancer
  vars_files:
      - variables/load-balancer.yaml
  user: citruspi
  roles:
  - nginx
  - ssl
  tasks:
  - name: Update Nginx config
    template: src=templates/load-balancer/nginx/nginx.j2 dest=/etc/nginx/nginx.conf
    sudo: True
    notify:
      - reload nginx
  - name: Update Nginx Site configs
    template: src=templates/load-balancer/nginx/{{item}}.j2 dest=/etc/nginx/conf.d/{{item}}.conf
    with_items: confs
    sudo: True
    notify:
      - reload nginx
