---
- hosts: load-balancer
  vars:
    nginx_conf: 'nginx'
    site_confs:
      - { conf: 'citruspi.io' }
      - { conf: 'mihirsingh.com' }
      - { conf: 'rhokthehood.com' }
    ssl_certs:
      - { cert: 'io.citruspi.www' }
      - { cert: 'com.rhokthehood.www' }
  user: citruspi
  roles:
  - nginx
  tasks:
  - name: Create project directory
    file: state=directory path=/etc/nginx/ssl
    sudo: True
  - name: Copy SSL certs
    copy: src=files/load-balancer/ssl/{{item.cert}}.crt dest=/etc/nginx/ssl/{{item.cert}}.crt mode=644
    with_items: ssl_certs
    sudo: True
    notify:
      - reload nginx
  - name: Copy SSL keys
    copy: src=files/load-balancer/ssl/{{item.cert}}.key dest=/etc/nginx/ssl/{{item.cert}}.key mode=644
    with_items: ssl_certs
    sudo: True
    notify:
      - reload nginx
  - name: Copy Diffie-Hellman parameter
    copy: src=files/load-balancer/ssl/dhparam.pem dest=/etc/nginx/ssl/dhparam.pem mode=644
    sudo: True
    notify:
      - reload nginx
  - name: Update Nginx config
    template: src=templates/load-balancer/nginx/nginx.j2 dest=/etc/nginx/nginx.conf
    sudo: True
    notify:
      - reload nginx
  - name: Update Nginx Site configs
    template: src=templates/load-balancer/nginx/{{item.conf}}.j2 dest=/etc/nginx/conf.d/{{item.conf}}.conf
    with_items: site_confs
    sudo: True
    notify:
      - reload nginx
  handlers:
  - name: reload nginx
    command: service nginx reload
    sudo: True
