---
- hosts: static
  vars_files:
    - variables/static.yaml
  user: deploy
  roles:
  - nginx
  tasks:
  - name: Confirmed static assets directory
    file: path=/srv state=directory owner=deploy
    sudo: True
  # GitHub Projects
  - name: Download GitHub projects
    get_url: url=https://github.com/{{item.owner}}/{{item.repo}}/archive/{{item.branch}}.zip dest=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}.zip
    with_items: gh_projects
  - name: Create temporary directories for GitHub project builds
    file: path=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}} state=directory
    with_items: gh_projects
  - name: Create permanent (domain-level) directory for GitHub project builds
    file: path=/srv/{{item.domain}} state=directory
    with_items: gh_projects
  - name: Unarchive GitHub project builds
    unarchive: src=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}.zip dest=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}} copy=no
    with_items: gh_projects
  - name: Remove legacy GitHub project builds
    file: path=/srv/{{item.domain}}/{{item.subdomain}} state=absent
    with_items: gh_projects
  - name: Place fresh GitHub project builds
    command: mv /tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}/{{item.repo}}-{{item.branch}} /srv/{{item.domain}}/{{item.subdomain}}
    with_items: gh_projects
  - name: Cleanup GitHub project build archives
    file: path=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}.zip state=absent
    with_items: gh_projects
  # Jenkins-built, S3-managed Projects
  - name: Download S3 project builds
    get_url: url=https://s3.amazonaws.com/{{item.bucket}}/{{item.branch}}-latest.zip dest=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}.zip
    with_items: s3_projects
  - name: Create temporary directories for S3 project builds
    file: path=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}} state=directory
    with_items: s3_projects
  - name: Create permanent (domain-level) directory for S3 project builds
    file: path=/srv/{{item.domain}} state=directory
    with_items: s3_projects
  - name: Unarchive S3 project builds
    unarchive: src=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}.zip dest=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}} copy=no
    with_items: s3_projects
  - name: Remove legacy S3 project builds
    file: path=/srv/{{item.domain}}/{{item.subdomain}} state=absent
    with_items: s3_projects
  - name: Place fresh S3 project builds
    command: mv /tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}} /srv/{{item.domain}}/{{item.subdomain}}
    with_items: s3_projects
  - name: Cleanup S3 project build archives
    file: path=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}.zip state=absent
    with_items: s3_projects
  - name: Update Nginx conf
    template: src=templates/static/nginx.j2 dest=/etc/nginx/conf.d/site.conf
    sudo: True
    notify:
       - reload nginx
  handlers:
  - name: reload nginx
    command: service nginx reload
    sudo: True
