---
- name: Confirmed static assets directory
  file: path=/srv state=directory owner={{user}}
  sudo: True
- name: Download S3 project builds
  get_url: url=https://s3.amazonaws.com/{{item.bucket}}/{{item.branch}}.zip dest=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}.zip
  with_items: front_end_projects
- name: Create temporary directories for S3 project builds
  file: path=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}} state=directory
  with_items: front_end_projects
- name: Create permanent (domain-level) directory for S3 project builds
  file: path=/srv/{{item.domain}} state=directory
  with_items: front_end_projects
- name: Unarchive S3 project builds
  unarchive: src=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}.zip dest=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}} copy=no
  with_items: front_end_projects
- name: Remove legacy S3 project builds
  file: path=/srv/{{item.domain}}/{{item.subdomain}} state=absent
  with_items: front_end_projects
- name: Place fresh S3 project builds
  command: mv /tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}} /srv/{{item.domain}}/{{item.subdomain}}
  with_items: front_end_projects
- name: Cleanup S3 project build archives
  file: path=/tmp/{{item.domain}}-{{item.subdomain}}-{{item.branch}}.zip state=absent
  with_items: front_end_projects
- name: Update nginx conf
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
  sudo: True
  notify:
    - reload nginx
- name: Update nginx site confs
  template: src={{item.conf}}.j2 dest=/etc/nginx/conf.d/{{item.conf}}.conf
  with_items: front_end_nginx_confs
  sudo: True
  notify:
    - reload nginx
