site_confs:
  - { conf: 'citruspi.io' }
app_confs:
  - { conf: 'wintergarten.conf' }
supervisor_confs:
  - { conf: 'wintergarten' }
python_projects:
  - { domain: 'citruspi.io', subdomain: 'wintergarten-api', repo: 'https://github.com/citruspi/Wintergarten-API.git', branch: 'master' }
